# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df1af68073747e56269a19faeaa13d098972795cb036d26705ecd6af5e171cc91e566bfce9a3142b0ca659f2b590d6f84479ae128bcf397fbe83758fe04e0a5

test:
  secret_key_base: 14ca5f5164fa776559db5cfb4f467e1a6919c56d7d06b8a24e0de0996abecba79623163d5e11eeb658efb89fc6320ea8266a1846830cd236e7e2ff46b5d23968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
